#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# - Create the mesh
runApplication blockMesh

# - Set initiation zone
runApplication setFields

# - Decompose computation domain
runApplication decomposePar

# -- run the calc in parallel
runParallel $(getApplication)

# ----------------------------------------------------------------- end-of-file
